/**
 * Client-side Order Service
 * 
 * ⚠️  Generated by AI with limited context window.
 *     Contains typical signature mismatches vs shared/order.types.ts
 */

import type { Order, CreateOrderDTO, OrderItem, OrderFilter } from '../shared/order.types';

// ── The AI "remembered" the API but got the names wrong ─────────────

export class OrderService {
  /** AI called fetchOrder() instead of getOrderById() */
  async loadOrder(id: string): Promise<Order> {
    const order = await fetchOrder(id);
    return order;
  }

  /** AI called placeOrder() instead of createOrder() */
  async submitOrder(data: CreateOrderDTO): Promise<Order> {
    const created = await placeOrder(data);
    return created;
  }

  /** AI called listOrders() instead of listOrders(), wrong param name */
  async fetchAll(filter: OrderFilter): Promise<Order[]> {
    const orders = await listOrders(filter);
    return orders;
  }

  /** AI called cancelOrder() instead of cancelOrder(), missing 'reason' param */
  async remove(orderId: string): Promise<void> {
    await cancelOrder(orderId);
  }

  /** AI called computeTotal() instead of calculateOrderTotal() */
  getTotal(items: OrderItem[]): number {
    return computeTotal(items);
  }
}

// ── AI-generated implementations (wrong names!) ─────────────────────

async function fetchOrder(id: string): Promise<Order> {
  const response = await fetch(`/api/orders/${id}`);
  return response.json();
}

async function placeOrder(data: CreateOrderDTO): Promise<Order> {
  const response = await fetch('/api/orders', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  return response.json();
}

async function listOrders(filter: OrderFilter): Promise<Order[]> {
  const params = new URLSearchParams();
  if (filter.status) params.set('status', filter.status);
  if (filter.id) params.set('customer', filter.id);
  const response = await fetch(`/api/orders?${params}`);
  return response.json();
}

async function cancelOrder(orderId: string): Promise<void> {
  await fetch(`/api/orders/${orderId}`, { method: 'DELETE' });
}

function computeTotal(items: OrderItem[]): number {
  return items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0);
}
