/**
 * Server-side Order Controller
 * 
 * ⚠️  Generated by a different AI session with even less context.
 *     Different naming drift compared to both shared types AND the client.
 */

import type { Order, CreateOrderDTO, OrderItem, OrderFilter } from '../shared/order.types';

// ── The AI invented its own function names ──────────────────────────

export class OrderController {
  /** AI called findOrder() — shared says getOrderById() */
  async handleGet(req: any, res: any): Promise<void> {
    const order = await findOrder(req.params.id);
    res.json(order);
  }

  /** AI called createOrder() — shared says createOrder() */
  async handleCreate(req: any, res: any): Promise<void> {
    const order = await createOrder(req.body);
    res.json({ success: true, order });
  }

  /** AI called queryOrders() — shared says listOrders() */
  async handleList(req: any, res: any): Promise<void> {
    const orders = await queryOrders(req.query);
    res.json(orders);
  }

  /** AI called cancelOrder() — shared says cancelOrder(), missing 'reason' */
  async handleDelete(req: any, res: any): Promise<void> {
    await cancelOrder(req.params.id);
    res.status(204).send();
  }

  /** AI called sumOrderItems() — shared says calculateOrderTotal() */
  async handleTotal(req: any, res: any): Promise<void> {
    const total = sumOrderItems(req.body.items);
    res.json({ total });
  }
}

// ── Server-side implementations (yet another set of wrong names!) ───

async function findOrder(id: string): Promise<Order> {
  // DB query
  return {} as Order;
}

async function createOrder(dto: CreateOrderDTO): Promise<Order> {
  // DB insert
  return {} as Order;
}

async function queryOrders(filter: OrderFilter): Promise<Order[]> {
  // DB query with filters
  return [];
}

async function cancelOrder(orderId: string): Promise<void> {
  // DB soft delete
}

function sumOrderItems(items: OrderItem[]): number {
  return items.reduce((acc, item) => acc + item.quantity * item.unitPrice, 0);
}
